# Generated by Django 4.0.4 on 2022-06-08 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130)),
                ('reply_to', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=130)),
                ('body', models.CharField(max_length=1500)),
                ('raw_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('url', models.CharField(max_length=255)),
                ('founded', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('contacts', models.EmailField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('buy', models.DecimalField(decimal_places=10, max_digits=100)),
                ('sale', models.DecimalField(decimal_places=10, max_digits=100)),
                ('source', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='currency.source')),
            ],
        ),
    ]
