# Generated by Django 2.2.12 on 2022-04-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_auto_20220402_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=5)),
                ('source', models.CharField(max_length=50)),
                ('created', models.DateTimeField()),
                ('buy', models.DecimalField(decimal_places=10, max_digits=100)),
                ('sale', models.DecimalField(decimal_places=10, max_digits=100)),
            ],
        ),
    ]
