# Generated by Django 4.0.4 on 2022-04-29 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0005_alter_contact_us_id_alter_rate_id_alter_source_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact_us',
        ),
    ]
