# Generated by Django 4.0.4 on 2022-04-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0006_delete_contact_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130)),
                ('reply_to', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=130)),
                ('body', models.CharField(max_length=1500)),
                ('raw_content', models.TextField()),
            ],
        ),
    ]
